name: subtify
services:
  subtify:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: subtify
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "blastbeng/subtify:latest"
    restart: always
    volumes:
      - ".env:/home/user/subtify/.env"
      - ".cache:/home/user/subtify/cache"
    entrypoint: ./entrypoint.sh
    ports:
      - 50811:50811
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:50811/utils/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 12