name: spotify-to-subsonic
services:
  spotify-to-subsonic-api:
    tty: true
    stdin_open: true
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      shm_size: "16gb"
    container_name: spotify-to-subsonic-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "blastbeng/spotify-to-subsonic-api:1.0.0"
    restart: always
    volumes:
      - ".env:/home/user/spotify-to-subsonic/.env"
      - ".cache:/home/user/spotify-to-subsonic/.cache"
      - "/var/media/musica:/var/media/musica"
    entrypoint: ./entrypoint.sh
    ports:
      - 50811:50811
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:50811/utils/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 12