name: spotisub
services:
  spotisub:
    container_name: spotisub
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SPOTIPY_CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXX
      - SPOTIPY_CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXX
      - SPOTIPY_REDIRECT_URI=http://127.0.0.1:8080/
      - SUBSONIC_API_HOST=http://127.0.0.1
      - SUBSONIC_API_PORT=4533
      - SUBSONIC_API_USER=user
      - SUBSONIC_API_PASS=pass
    image: "blastbeng/spotisub:latest"
    restart: always
    volumes:
      - "./cache:/home/user/spotisub/cache"
    entrypoint: ./entrypoint.sh
    ports:
      - 5183:5183
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5183/utils/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 12
